apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: gcr.io/kubernatives-388300/container1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: persistent-storage
              mountPath: /shubh_PV_dir 
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: my-pvc
